---
title: "BikeShare"
author: "Liam Durkin"
date: "2022-10-28"
output: html_document
---

```{r}
library(dplyr)
library(janitor)
library(tidyverse)
library(lubridate)
```

```{r}
bikeshare <- read.csv("bikeshare_data.csv") %>% clean_names()
```

```{r}

bikeshare %>% ggplot(mapping = aes(start_lng, start_lat)) + geom_point()
```

```{r}

bikeshare %>% 
  filter(end_lat > 0) %>% 
  ggplot(mapping = aes(end_lat, end_lng)) + geom_point()
  
```

```{r}
df_hw <- bikeshare %>%
  mutate(start_time = floor_date(ymd_hms(started_at), unit = "hour")) %>%
  mutate(end_time = floor_date(ymd_hms(ended_at), unit = "hour"))
```

```{r}
dfa <- bikeshare %>%
  mutate(started_at = as.POSIXct(started_at)) %>%
  mutate(ended_at = as.POSIXct(ended_at))

```


```{r}
dfa <- dfa %>%
  mutate(duration = as.numeric((dfa$ended_at-dfa$started_at)/60), 
         hour_of_day = hour(started_at), 
         day_of_week = wday(started_at), 
         label = T) %>%
  filter(duration<100, duration >0)
```

```{r}
dfa %>% ggplot(mapping = aes(x = duration)) + geom_histogram(bins = 300) + facet_wrap(~day_of_week)
```

```{r}
dfb = dfa %>% filter(duration > 0)

dfb <- dfb %>%
  mutate(start_time = floor_date(ymd_hms(started_at), unit = "hour")) %>%
  mutate(end_time = floor_date(ymd_hms(ended_at), unit = "hour"))
```

```{r}
dfb %>%
  filter(month(started_at)==9,month(ended_at)==9) %>%
  select(rideable_type, start = started_at, end = ended_at) %>%
  pivot_longer(start:end, names_to="type",values_to="t") %>% arrange(t) %>%
  mutate(increment=case_when(
    type=="start" ~  1,
    type=="end"   ~ -1
  )) %>%
  group_by(rideable_type) %>%
  mutate(riders=cumsum(increment)) %>%
  filter(mday(t) <= 7) %>%
  ggplot(aes(t,riders, color = rideable_type)) + geom_step() + facet_wrap(~mday(t), scales="free_x",ncol=7)
  
  
  
  
```

```{r}
dfb %>%
  filter(month(started_at)==9,month(ended_at)==9) %>%
  select(member_casual, start = started_at, end = ended_at) %>%
  pivot_longer(start:end, names_to="type",values_to="t") %>% arrange(t) %>%
  mutate(increment=case_when(
    type=="start" ~  1,
    type=="end"   ~ -1
  )) %>%
  group_by(member_casual) %>%
  mutate(riders=cumsum(increment)) %>%
  #filter(mday(t) <= 7) %>%
  ggplot(aes(t,riders, color = member_casual)) + geom_step() + facet_wrap(~mday(t), scales="free_x",ncol=7)
```

```{r}
dfb %>% 
  filter(day(started_at) == 1) %>%
  ggplot(aes(x = duration)) + geom_histogram(binwidth = 5) + facet_wrap(~hour(start_time), scales='free_x', ncol=6)
  #histogram in 15 minute bins
```